services:
  postgresql:
    # https://github.com/docker-library/docs/blob/master/postgres/README.md
    # https://hub.docker.com/_/postgres/
    image: postgres:17.5-alpine
    container_name: postgresql
    restart: unless-stopped
    env_file: ./postgres.env
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      # stack-back limitation: only backs up POSTGRES_DB. Stop the container instead
      # https://stack-back.readthedocs.io/en/latest/guide/configuration.html#postgres
      stack-back.postgres: false
      stack-back.volumes: true
      stack-back.volumes.include: "postgresql_data"
      stack-back.volumes.stop-during-backup: true

      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: asot

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # consumers
          - network: common_backend
            container: outline
          - network: common_backend
            container: authentik-server
          - network: common_backend
            container: authentik-worker
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql_data:
