# XFER STACK
## Per-stack instances of services (e.g. for backups) are declared here.
services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${GLUETUN_PROVIDER}
      - VPN_TYPE=${GLUETUN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WG_PRIVATE_KEY}
      - SERVER_COUNTRIES=${GLUETUN_COUNTRIES}
      - SERVER_CITIES=${GLUETUN_CITIES}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: xfer

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      # streammaster
      traefik.http.routers.streammaster-http.rule: Host(`stm.${DOMAIN}`)
      traefik.http.routers.streammaster-http.entrypoints: http
      traefik.http.routers.streammaster-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      # streammaster
      traefik.http.routers.streammaster-https.rule: Host(`stm.${DOMAIN}`)
      traefik.http.routers.streammaster-https.entrypoints: https
      traefik.http.routers.streammaster-https.tls: true
      traefik.http.routers.streammaster-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.streammaster-https.service: streammaster
      traefik.http.routers.streammaster-https.middlewares: crowdsec-bouncer

      # streammaster
      traefik.http.services.streammaster.loadbalancer.server.port: 9191

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration. 
include:
  # - ./dispatcharr/docker-compose.yaml
  - ./nzbhydra2/docker-compose.yaml
  - ./prowlarr/docker-compose.yaml
  - ./streammaster/docker-compose.yaml
