# XFER STACK
## Per-stack instances of services are declared here.

# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration. 
include:
  - ./dispatcharr/docker-compose.yaml
  - ./gluetun/docker-compose.yaml
  - ./nzbhydra2/docker-compose.yaml
  - ./prowlarr/docker-compose.yaml
  - ./streammaster/docker-compose.yaml
