services:
  ownfoil:
    # https://hub.docker.com/r/a1ex4/ownfoil/tags
    image: a1ex4/ownfoil:2.1.3
    container_name: ownfoil
    restart: unless-stopped
    environment:
      # https://github.com/a1ex4/ownfoil#docker-compose
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_SHARED_GID}
      - USER_ADMIN_NAME=${HINOX_ADMIN_USER}
      - USER_ADMIN_PASSWORD=${HINOX_ADMIN_PASSWORD}
      - USER_GUEST_NAME=${HINOX_USER}
      - USER_GUEST_PASSWORD=${HINOX_PASSWORD}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: asot-media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.ownfoil-http.rule: Host(`hnx.${DOMAIN}`)
      traefik.http.routers.ownfoil-http.entrypoints: http
      traefik.http.routers.ownfoil-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.ownfoil-https.rule: Host(`hnx.${DOMAIN}`)
      traefik.http.routers.ownfoil-https.entrypoints: https
      traefik.http.routers.ownfoil-https.tls: true
      traefik.http.routers.ownfoil-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.ownfoil-https.service: ownfoil
      traefik.http.routers.ownfoil-https.middlewares: crowdsec-bouncer

      traefik.http.services.ownfoil.loadbalancer.server.port: 8465

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - ${GAMES_ROOT}:/games
      - ownfoil_config:/app/config
    networks:
      - backend

volumes:
  ownfoil_config:
