# https://getsops.io/docs/#using-sopsyaml-conf-to-select-kms-pgp-and-age-for-new-files
creation_rules:
  - path_regex: .*hzfsn1-18-1.*
    age: 'age1nzak27uave7mxuhqvuh67me3pul29z3yjqhur46grmx4x0mfju7syasnup'
