services:
  portainer:
    image: portainer/agent:2.27.6
    container_name: portainer-agent
    group_add:
      - ${DOCKER_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      - COMPOSE_UNPACKER_IMAGE=jbruns/compose-unpacker:2.21.3-sops
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: common

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        mapped_ports:
          external:
            allow: true
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/portainer_unpack:/var/portainer_unpack
    networks:
      - backend
