services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy:2025.4.1
    container_name: authentik-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      AUTHENTIK_HOST: https://idp.${DOMAIN}
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: ${AUTHENTIK_TOKEN}
    labels:
      traefik.enable: true
      
      ## Authentik forward auth middleware
      traefik.http.middlewares.authentik.forwardAuth.address: "http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik"
      traefik.http.middlewares.authentik.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardAuth.authResponseHeaders: "X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version"

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # reverse proxy
          - network: common_backend
            container: traefik
    networks:
      - backend