#ENC[AES256_GCM,data:CKCsazKHGYhsPhleMy71xKVJT/K62w9AYG3tg/pMhu5xMjjxScKqcV+A2hsJSgwAKqbI5XiwrKMc/V7HDg==,iv:rEdOICQnCgL1wivOmnmEo/VWdFHYMZC40ozrIzaZQdQ=,tag:f++gEMtfb9C7zArC/8ZtJw==,type:comment]
#ENC[AES256_GCM,data:PdXnCiOAx70DpJHQCk9djZIudK7F42ZCbOW6Kez1w9DnWBHNuoVOQw9zsNdx5hGxV0bksUCjAb2y1fpqtCjiSduOoV9O77h4PeRTd+dYyUpOotkxi0XCDMJLeYujhVAwZyqiYD+15RPnG+xZbjzLu3yZnlWN0uSoY+2MaG0aUezV2Hx0,iv:AEykGxEt5YK7Ct31JQaHuj8MZPcPPq4h+f3n1A3mP8M=,tag:YLFNmr1N7irt28G8nuvelQ==,type:comment]
basic_auth_users:
    asotadmin: ENC[AES256_GCM,data:WqX5yB44rP5zd+vIjOREdcHml8JV8dNICtEpJIgT38/VKOhK50LDStrBeYd2CogRrakR8dL0yHPZ4r89,iv:ZKMXHX4bXnCjXZ8iQFCzf708GiAcjV6LkBLUBBGw9Qc=,tag:TjzVk0JBv/xmopVWb+CRuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nzak27uave7mxuhqvuh67me3pul29z3yjqhur46grmx4x0mfju7syasnup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ3lyWjhQcEpueDhOVFRw
            M2VzSmZFOXltZnZHak55dEpuOXh5b3d0N1dvClRzZmZVVGNFZ0lCcTFFMkh2Tk9l
            VEhGM2FkYUtmdmRJeCsyNnlGbFBFYm8KLS0tIEIwNmdXZkhQQ255L29DaUsxT0U0
            NEpQKzZCRE9pQkZ2ODkxVUwxc2lTczQK2/gY/2iYxbGQ+r4F0v/OZ9k/cP8Vy2BP
            0Uu3sTSB9HKCAvbdEUgXmkMWgSQYSnP1f/TH7wHBCz9admlogcluuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T17:23:39Z"
    mac: ENC[AES256_GCM,data:2ersW6RfOa5P2Jmk7Trr8+SY1S2jazhm8CM3XQbexq3Fa9c+93uB6W7WtmEHlafUhYlkxcohzlSMaE2lTdIM88vrkGsy2JvZ/5pe1w3Gcrgb69Tg8kccuFd5oE9xmqfkgDMbkyCG2IxW0yw9mBrwZlRUb3HyEtgdgt1QZOjbCII=,iv:GKf2/0d8fZEDA6kJZaJNrH8UitPwwcTN2itfHcjMaLs=,tag:j4R/asOwP8V2LRiHAC8t/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
