# MEDIA STACK
## Per-stack instances of services (e.g. for backups) are declared here.
services:
  asot-media-backup:
    restart: unless-stopped
    # https://github.com/offen/docker-volume-backup    
    image: offen/docker-volume-backup:v2.43.4
    container_name: asot-media-backup
    environment:
      # https://offen.github.io/docker-volume-backup/reference
      - BACKUP_FILENAME=asot-media-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=20 2 * * *
      - BACKUP_PRUNING_PREFIX=asot-media-
      - BACKUP_RETENTION_DAYS=7
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: asot-media

      # network policy
      whalewall.enabled: true
      # backup: no traffic in or out
    volumes: 
      # Backup source volumes
      # abs
      - audiobookshelf_config:/backup/audiobookshelf_config:ro
      - audiobookshelf_metadata:/backup/audiobookshelf_metadata:ro
      - audiobookrequest_config:/backup/audiobookrequest_config:ro
      # cwa
      - calibre-web-automated_config:/backup/calibre-web-automated_config:ro

      # Backup target
      - ${ZFS_POOL_ROOT_HDD}/docker-backups:/archive
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration. 
include:
  - ./abs/docker-compose.yaml
  - ./authentik-proxy/docker-compose.yaml
  - ./cwa/docker-compose.yaml
  - ./ownfoil/docker-compose.yaml
