services:
  readarr:
    # https://github.com/linuxserver/docker-readarr
    # https://hub.docker.com/r/linuxserver/readarr/tags
    image: ghcr.io/linuxserver/readarr:0.4.17-develop
    container_name: readarr
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_SHARED_GID}
      - TZ=${TZ}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: asot-media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.rdr-http.rule: Host(`rdr.${DOMAIN}`)
      traefik.http.routers.rdr-http.entrypoints: http
      traefik.http.routers.rdr-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first      
      traefik.http.routers.rdr-https.rule: Host(`rdr.${DOMAIN}`)
      traefik.http.routers.rdr-https.entrypoints: https
      traefik.http.routers.rdr-https.tls: true
      traefik.http.routers.rdr-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.rdr-https.service: cwa
      traefik.http.routers.rdr-https.middlewares: cwa-chain

      traefik.http.services.rdr.loadbalancer.server.port: 8787

      traefik.http.middlewares.rdr-chain.chain.middlewares: crowdsec-bouncer,authentik

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - readarr_config:/config
      - ${ZFS_POOL_ROOT_HDD}/media:/data
    networks:
      - backend

volumes:
  readarr_config:
