# KB STACK
## Per-stack instances of services (e.g. for backups) are declared here.

# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration. 
include:
  - ./outline/docker-compose.yaml
  - ./postgres/docker-compose.yaml
  - ./redis/docker-compose.yaml
