# MONITORING STACK
## With thanks to https://github.com/ruanbekker/docker-monitoring-stack-gpnc
## Per-stack instances of services (e.g. for backups) are declared here.
services:
  monitoring-backup:
    restart: unless-stopped
    # https://github.com/offen/docker-volume-backup    
    image: offen/docker-volume-backup:v2.43.4
    container_name: monitoring-backup
    environment:
      # https://offen.github.io/docker-volume-backup/reference
      - BACKUP_FILENAME=hzfsn1-18-1-monitoring-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=30 2 * * *
      - BACKUP_PRUNING_PREFIX=hzfsn1-18-1-monitoring-
      - BACKUP_RETENTION_DAYS=7
    env_file: ./backup.env
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
    volumes: 
      # Backup source volumes
      # alertmanager
      - alertmanager_data:/backup/alertmanager_data:ro
      # grafana
      - grafana_data:/backup/grafana_data:ro
      # prometheus
      - prometheus_data:/backup/prometheus_data:ro
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend
        
# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration.
include:
  - ./alertmanager/docker-compose.yaml
  - ./cadvisor/docker-compose.yaml
  - ./grafana/docker-compose.yaml
  - ./loki/docker-compose.yaml
  - ./node-exporter/docker-compose.yaml
  - ./prometheus/docker-compose.yaml
  - ./promtail/docker-compose.yaml
