services:
  prowlarr:
    # https://github.com/home-operations/containers/pkgs/container/prowlarr
    # https://github.com/prowlarr/prowlarr
    image: ghcr.io/home-operations/prowlarr:1.34.1
    user: ${XFER_UID}:${XFER_GID}
    security_opt:
      - no-new-privileges=true
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      # traefik: see gluetun container

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - prowlarr_config:/config
    network-mode: "service:gluetun"

volumes:
  prowlarr_config:
